/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String GTSectraFineRegular = "assets/fonts/GT Sectra Fine Regular.ttf";
  static const String Logo = "assets/images/Logo.png";
  static const String lottieloading = "assets/images/lottieloading.json";
  static const String No_Image_Placeholder = "assets/images/No-Image-Placeholder.png";
  static const String test_image = "assets/images/test_image.png";
}
